Update training-l3.yaml
aristanetworks/training-infra-public pull request #38
Opened 2024-02-05 19:47 UTC by sasakariz1

add Host-1 Base for Lab Reset Host-11 and Host-12 Base for lab reset

2024-02-05 21:06 UTC, rparkinarista approved these changes

2024-02-05 21:09 UTC, rparkinarista requested changes
The original lower case version was correct, I believe. The devices use lower case in the topo_build file and the configlets are lower case too.

2024-02-06 06:48 UTC, sasakariz1 reviewed
I used small host-1-BASE did you change it to capital? Is that ok?

2024-02-06 09:00 UTC, rparkinarista commented
Not sure then, the merge request had uppercase 

￼
But at the same time it looks like you also pushed another change, without a pull request to add the smae items in but in lower case.

￼

Looks like the first one was correct and you didn’t need the change in the pull request.

Thanks
Rich

> On 6 Feb 2024, at 06:48, Saša Kariz ***@***.***> wrote:
> 
> 
> @sasakariz1 commented on this pull request.
> 
> I used small host-1-BASE did you change it to capital? Is that ok?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/aristanetworks/training-infra-public/pull/38#pullrequestreview-1864390141>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AKV5N5VNTCG4B2FURDJA3ILYSHG4JAVCNFSM6AAAAABC2XRUISVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRUGM4TAMJUGE>.
> You are receiving this because your review was requested.
>

2024-02-06 10:20 UTC, closed without merging